export const SWITCH_SHOW_CALCULATOR = 'SWITCH_SHOW_CALCULATOR';
export const SWITCH_SHOW_HOURS = 'SWITCH_SHOW_HOURS';
export const SWITCH_SHOW_MINUTES = 'SWITCH_SHOW_MINUTES';
export const SET_CURRENT_HOURS = 'SET_CURRENT_HOURS';
export const SET_CURRENT_MINUTES = 'SET_CURRENT_MINUTES';